* Meeting minutes
** SC meetings
*** <2016-11-22 Tue>
    - Write a document which includes
      1. Common machine configuration
	 1. LSN plasma
	 2. B\times\nabla B pointing towards the active X-point
	 3. Fueling location. Check where the valves are
	 4. Heating (Ohmic for L-Mode) NBI for the H-Mode
	 5. Outer gap in term of \rho_s
	 6. Running TCV at z=+8 with larger outer gap. 
      2. Common measuring technique
	 1. Measurement of divertor collisionality
	    1. See Topic of Mathias Berndt for the reconstruction of divertor properties
	    2. Is there any possible way to have Te and ne along the field line? DSS? 
	 2. Measurement of fluctuations
	 3. Measurement of neutrals
      3. Long statistics only on wall mounted probe because of limited amount of time available
      4. PPY for TFL 
      
*** <2017-02-20 Mon>
**** Agenda 
     - Discussion on Shotlist for AUG experiment. See preliminary
     - Diagnostic request
     - Experimental analysis request and identification of key persons
     - Identification of relevant SL to be contacted
** Other Meetings
*** Neutral measurement meetings
    <2016-12-01 Thu>
    Attendes: J. Madsen (JM), B. Lipschultz (BL), F. Militello (FM),
              N. Vianello (NV), M. Agostini (MA), P. Scarin (PS)
    - NV ask for clarification regarding the paper circulated by Bruce.
    - BL clarify that the difference between foil bolometer and AXUV is only needed
      if one need the power emission from neutrals. If the aiming is the determination
      of neutral density this is not needed
    - BL clarify that to get neutral density for AXUV one need diods with Lyman-a
      filter, looking toroidally for proper Abel inversion to be coupled with density and
      temperature profile
    - JM and FM suggest that careful must be used for interpretation as one get density and temperature
      profile as a sort of /*statistical object*/ wheras extraction of density profile from emission
      is a strong non-linear process
    - If camera needs to be used rather then diods then we need to get rid of reflection with appropriate
      view dump. Can be less a proble in graphite machines due to lower reflection from graphite with respect
      to W
    - Is Lyman-a optically thin?
    - Agreed on following steps
      - [ ] check Camera's and AXUV on TCV: view location, resolution, view dump, filters  (NV)
      - [ ] check Camera's and AXUV on AUG: view location, resolution, view dump, filters (JM)
      - [ ] check Camera's and AXUV on MAST-U: view location, resolution, view dump, filters (FM)
*** AUG experimental planning meeting
    <2017-02-23 Thu>
    - Choose a different reference shot 30269 where we have also 300 kW ECRH
    - We need to check if changes in carrent and changes in q95 changes the entire
      shaping
    - Strike point sweeping can be used for diagnostic purpouse to provide better
      resolved divertor profiles
    - H-Mode reference shot from internal campaign (See PSI table last shot)
    - Different approach proposed for H-Mode
      1. Take scenario, at increased NB power (6 MW). Density ramp adjusted from
	 reference. 1 Plunge in safe position of the probe
      2. Repeat #1 eventually adjusting the fueling and add N seeding in
	 feedforward
      3. Find the optimum betwee #1 and #2
      4. Repeat #3 with probe at different position
      5. Repeat #3 with probe at different position
      6. Repeat at reduced Cryopump
      7. Repeat with puffing from the midplane
