* Shotlist for TOPIC 21
** AUG:
   Available number of Shots #14
*** L-Mode investigation: Forseen number 6
    1. Choose fueling levels for reference shot at 0.8 MA from AUG14-2.2-3 #30276. Perform the same density ramp at 0.6 MA
       by keeping the same Toroidal Field
    2. Repeat Shot #1 by keeping the same q_{95} as reference
    3. Repeat Shot #30276 @ 1MA with the same toroidal field
    4. Repeat #3 by keeping the same q_{95} as the reference
    5. Repeat #30276 with Reverse Bt
    6. Repeat #5 with Probe at different insertion
    
*** H-Mode investigation: Foreseen number 9
    The reference shot is 33059 (AUG15-2.2-3) with the aim to reach the condition found in 31607 (Sun PPCF 2015)
    1. Scenario development. Start from succesful shot 33059 (Total heating 3.1 MW),
       keep the probe head in a safe position (FAR SOL) increase the heating power (two steps to 4.5 and 6) up to 6 MW
       monitoring midplane probe by IR and Divertor through Langmuir.
    2. Repeat #1 Fueling ramps according to reference. Monitor of Divertor condition
    3. Repeat #2 adjusting eventually the fueling and N seeding ramp monitoring the Divertor condition
    4. Repeat #4 with optimum level of Fueling/Seeding 1st Radial position of probe
    5. Repeat #5, different probe position
    6. Repeat #6, different probe position
    7. Repeat #6 with Strike-point sweeping (if feasible)
    8. Contingency
    9. Contingency
 
** TCV 
   Available number of Shots #23 
*** L-Mode: Forseen number 11
    The reference shape is a LSN with a ion BxgradB pointing towards the X-point as in
    #53514 @0.6s. Density ramp with Line average density from 3.5e19 to 8.2e19 Ip @ 240kA.
    Plasma vertical position Z=+8cm to increase the SOL region in front of the probe
    1. Perform reference shot with 2 RCP stroke and SP sweeping for better coverage of target probe
    2. Repeat #1 with strokes at different timing 
    3. Repeat #1 @ 160kA with stroke at the timing of maximum variation of the profiles according to #1-2
       keeing Bt constant
    4. Repeat #3 eventually reducing the Drate and repeat #3
    5. Repeat #1 @ 300kA with the same density ramp and strokes according to #3 keeping Bt constant
    6. Repeat #1 @ 300kA increasing the Drate up to Line average density of 9e19
    7. Repeat #1 with strokes according to best timing from #1-#2 but with Reverse Bt
    8. Drate from #1, Ip=240kA, Z=+23 strokes from #7
    9. Drate from #1, Ip=240kA, Z=-10 strokes from #7
    10. Repeat #3 keeping q95 constant with respect to #1
    11. Repeat #10 for diagnostic purpouse

*** H-Mode: Forseen number 12
    Reference shot for Type I ELMy H-Mode from TCV15-2.3-1 #53352 with Z=+8cm, still compatible
    with NBI operation. The ELM frequency is 100Hz approximately
    1. Repeat #53352 with probe plunge in L and H-mode. Check robustness of Probe signal in H-mode, eventually adjust
       maximum insertion
    2. Repeat #53352 D2 density ramp once H-Mode is established. 
    3. Check maximum density achieved before H-Mode degradation or disruption. Density feedback to
       this value during H-Mode. NBI power ramp down to check for ELMy regime
    4. Repeat #3 for diagnostic purpouse
    5. repeat #3 in the High-Density phase start N-seeding. Use seeding rate from Detachment experiment
       in L-Mode as starting point
    6. Evaluation of #6 in terms of divertor condition. Choose the right N-seeding values and repeat
    7. Repeat #6, anticipate the NBI power, keep density and N-seeding after the H-L transition. Plunge also in L-Mode
    8. Repeat #7 for diagnostic purpouse
    9. Repeat #8. If feasible decrease vertical position @ Z=-8cm
    10. Contingency
    11. Contingency
    12. Contingency

** MAST-U
   Foreseen number of shots 13
*** L-Mode: Foreseen 6 shots
    1. Density ramp at 400 kA on midplane manipulator up to density where shoulder will appear
       Fueling from the divertor common flux region
    2. Repeat #1 at 800kA with constant Bt
    3. Repeat #2 at 800kA with constant q95 with respect to #1
    4. Repeat #1 with fueling at upstream LFS
    5. Repeat #1 with RFA to get information on Ti
    6. Repeat #4 with RFA to get information for Ti
*** H-Mode: Forseen 7 Shots
    The H-Mode scenario need to be well developed and eventually this part may be
    move to 2018 if scenario not found
    1. Type-I H mode with fueling increase in from the same location of #1 L-Mode plasma. Determine
       proper density value for broadening (if any)
    2. Repeat #1 at target density for broader profile for diagnostic purpose
    3. Repeat #1 keep density below threshold for broadening (if any). N seeding
    4. Determine optimum for N seeding to keep radiation in within the SOL (no X-point radiation)
       Is there any N seeding feedback foreseen?
    5. Repeat #1 at changing the connection length (e.g change of the gap between divertor baffle or moving from SN to DN)
    6. Repat #5 with seeding
    7. Contingency

