* Meeting minutes
** SC meetings
*** <2016-11-22 Tue>
    - Write a document which includes
      1. Common machine configuration
	 1. LSN plasma
	 2. B\times\nabla B pointing towards the active X-point
	 3. Fueling location. Check where the valves are
	 4. Heating (Ohmic for L-Mode) NBI for the H-Mode
	 5. Outer gap in term of \rho_s
	 6. Running TCV at z=+8 with larger outer gap. 
      2. Common measuring technique
	 1. Measurement of divertor collisionality
	    1. See Topic of Mathias Berndt for the reconstruction of divertor properties
	    2. Is there any possible way to have Te and ne along the field line? DSS? 
	 2. Measurement of fluctuations
	 3. Measurement of neutrals
      3. Long statistics only on wall mounted probe because of limited amount of time available
      4. PPY for TFL 
      
*** <2017-02-20 Mon>
**** Agenda 
     - Discussion on Shotlist for AUG experiment. See preliminary
     - Diagnostic request
     - Experimental analysis request and identification of key persons
     - Identification of relevant SL to be contacted
*** <2017-05-10 Wed>
**** Agenda
     - Make Volker aware of the AUG experimental plan
       completed and to be done
**** Minutes
     - Discussed the obtained shots in W17. There are some
       questions concerning the response of the divertor gauges to
       increasing puffing.
     - Discussed briefly foreseen shots for W21. Tentative schedule
       1. Repeat Shot 34115 with more strokes in a more inserted position
       2. Repeat #1 if further statistics is needed
       3. Repeat #1 but with cryopumps to check dependence on divertor
	  neutral density
       4. Increase the fueling rate trying to match midplane density
	  density profile evolution
       5. Repet #4 for better probe statistics (second radial position)
       6. Repeat #4 with midplane fueling
       7. Contingency
**** TODO To-DO [0/3]
     - [ ] Compute proper neutral compression using all available gauges
     - [ ] Check for time delay in divertor neutral pressure to increasing
           fueling
     - [ ] Organize a meeting, tentative for Wednesday 16 for preparation of W21
     
*** Program for 2018 <2017-10-31 Tue>
**** TCV
     1. Long divertor legs (probe in the lower port)
     2. SnowFlake to monitor the fluctuations in between the 2 separatrix
	to be done in high density discharges
     3. Try to move the second X-point in SN divertor at a different
	Z position while keeping the same radial distances between the
	points
     4. H-Mode ?
**** AUG
     1. X-point manipulator (hopefully with NPH) triggered at
	the same time as MPM
     2. X-point vertical shift in order to have SP at different
	vertical heigth at the target
     3. DN discharges. With slow movement of the second X-point into the vessel
	to be performed at constant power/density where shoulder alreay exists
     4. USN with midplane/X-point manipulator to monitor the upstream SOL
**** MAST-U
     1. Influence of neutral recycling source in establishing upstream profiles
	and comparison between Low-RT and Vertical target. Look also ath the heat
	loads
     2. Current scan at constant q95/constant Bt
    
** Other Meetings
*** Neutral measurement meetings
    <2016-12-01 Thu>
    Attendes: J. Madsen (JM), B. Lipschultz (BL), F. Militello (FM),
              N. Vianello (NV), M. Agostini (MA), P. Scarin (PS)
    - NV ask for clarification regarding the paper circulated by Bruce.
    - BL clarify that the difference between foil bolometer and AXUV is only needed
      if one need the power emission from neutrals. If the aiming is the determination
      of neutral density this is not needed
    - BL clarify that to get neutral density for AXUV one need diods with Lyman-a
      filter, looking toroidally for proper Abel inversion to be coupled with density and
      temperature profile
    - JM and FM suggest that careful must be used for interpretation as one get density and temperature
      profile as a sort of /*statistical object*/ wheras extraction of density profile from emission
      is a strong non-linear process
    - If camera needs to be used rather then diods then we need to get rid of reflection with appropriate
      view dump. Can be less a proble in graphite machines due to lower reflection from graphite with respect
      to W
    - Is Lyman-a optically thin?
    - Agreed on following steps
      - [ ] check Camera's and AXUV on TCV: view location, resolution, view dump, filters  (NV)
      - [ ] check Camera's and AXUV on AUG: view location, resolution, view dump, filters (JM)
      - [ ] check Camera's and AXUV on MAST-U: view location, resolution, view dump, filters (FM)
*** AUG experimental planning meeting
    <2017-02-23 Thu>
    - Choose a different reference shot 30269 where we have also 300 kW ECRH
    - We need to check if changes in carrent and changes in q95 changes the entire
      shaping
    - Strike point sweeping can be used for diagnostic purpouse to provide better
      resolved divertor profiles
    - H-Mode reference shot from internal campaign (See PSI table last shot)
    - Different approach proposed for H-Mode
      1. Take scenario, at increased NB power (6 MW). Density ramp adjusted from
	 reference. 1 Plunge in safe position of the probe
      2. Repeat #1 eventually adjusting the fueling and add N seeding in
	 feedforward
      3. Find the optimum betwee #1 and #2
      4. Repeat #3 with probe at different position
      5. Repeat #3 with probe at different position
      6. Repeat at reduced Cryopump
      7. Repeat with puffing from the midplane
*** KoM-AUG 03.03.2017
    - The first remark is the observation that TCV experiment crashes with the
      ITPA Div-SOL meeting. As a consequence *SC must check presence of
      relevant people otherwise ask for postponing the experiment*
    - Presentation of Experimental plan of D. Carralero:
      + F. Militello suggest that q95 scan can provide as a consequence
	a changes of beta and consequently of the MHD activity. /Need to check
	of possible existing scenarios at different current/
      + N. Walkden propose the development of synthetic diagnostic to compare
	with Probe and furthermore ask for the presence of GPI data
      + I. Cziegler comments on the improvement of GPI which in any case will not be
	available for the April campaign
      + As Response to that A. Hakkola suggests for askign for contingency at the
	end of the campaign for GPI+ APD channels
    - Presentation of W. Zhang: density scan during ICRF heated plasmas. Can this be combined
      with existing scenario foreseen for H-Mode? Actually he proposed to scan heating at constant density
    - Presentation of K. McClements:
      + The request of collisionality scan to obtain different ELM sizes can be obtained as piggy back
	during the main experiment
      + A fixed FILD diagnostic is available and can be operated during the campaign
      + The SXR should be added as required diagnostic but in any case is routinely available
    - Presentation of J. Vicente
      + The present setup is available only for density up to 3x10^19 band. /Is this sufficient for
	SOL exploration even at high density?/
      + Proposed density steps rather then ramps. /Is this a real requirements in order to have reliable
	measurements?/
    - General remarks:
      + Changes of cryopumps require to schedule the shot as 1st shot of the day
      + Reversing the Bt should be done together with reverse of Ip (same helicity) so to be included
        in the campaign foreseen for November. /Is this a
	requirement even for 300 kW L-Mode plasmas?/
      + J. Vicente asks if in a well established H-Mode we could think of a phase of discharge where a second
	null is bring into the vessel. Mathias commented that this would require a lot of development. /Can we
	attach a session leader to help us in designing the discharge?/
      + Li-Beam operation is ensured and manned during the campaign. Profile and fluctuations are available at the
	same time
      + Bolometer/AXUV will be manned during the operation but analysis should be asked. /Can we find appropriate
	resources?/
      + ECE/SXR for particle accelleration are a required diagnostic. Routinely in operation but analysis
	should be asked. /Can CCFE people take care of these analysis?/
      
*** AUG Preparation meeting 11.04.2017
    *Participants* : N. Vianello (NV),  D. Carralero (DC),  M. Bernert (MB), A. Hakola (AH)
**** Agenda:  
     1. Issue on shape at different current. We can match the shape from the reference and keep
	  constant during the discharge adusting current/field/heating?
     2. Issue on central heating. How broad is the profile? We do not need /central heating/ in the
	  sense inside the q=1
     3. Constant Bt or constant Ip scan?
     4. Multichannel reflectometer would prefer 1.9 T even though 1.8  is reasonable
**** Discussion and To Do
     - ECRH is not feasible at all the toroidal field proposed since even at lower frequency
       the cut-off is outside of the plasma
     - We propose to use NBI (500 kW) for all the discharge in order to ensure a more comparable
       heating throughout the q95 and Bt scan
     - We decide not to use the reference from G. Birkenmeir paper since they didn't keep
       inner and outer gap constant during the discharge. We prefer to use *EOC* shape and adjust current
       and toroidal field
     - The new L-Mode scan proposed is the following: I propose to keep the strike point sweeping
       at the end of the discharge for Divertor Profile resolution
       1) Reference shot 0.8 MA (as #30269, Bt = -2.5T) with 0.5 MW of NBI starting
	  at the beginning of the fueling ramp
       2) Shot at q_{95}=4.95 as #1, toroidal field 1.9T current to be determined with the same
	  NBI program. Reduce the fueling rate (order 20/%)
       3) Shot at q_{95}=4.95 I_p=1.1MA toroidal field accordingly chosen (approximately 3.5T). Still
	  500 kW NBI, increase the fueling rate
       4) Shot with B_t=2.5T, I_p as #3
       5) Shot with B_t=2.5T, I_p as #2
     - The H-Mode proposed plan is the following:
       1. Repeat # 33478 with P_{NBI} = 4MW with D_2 puffing from 4s reaching value of 40 10^{21}s^{-1}
	  @ 6s (/are the number correct according to the suggestion of Mathias?/)
       2. Repeat #1 adding the N seeding in feed-forward. Adjust the power according to ELM frequency
	  and probe behavior in #1
     - List of thigns to be done [0/4]
       - [ ] Determine the current for Shot #2 of L-Mode scan (DC)
       - [ ] Ask for TRANSP analysis of reference shot and eventually interpretative analysis
	 at smaller and larger current (NV/DC)
       - [ ] Insert experimental plan in EUROfusion Wiki (NV)
       - [ ] Insert the shot request in AUG system (DC)
       
*** KoM-TCV 15.05.2017
    Attendees: N. Vianello (NV), V. Naulin (VN), M. Bernert (MB), A. Hakola (AH), F. Militello (FM),
    C. Theiler (CT), C. Tsui (CT), B. Labit (BL), R. Maurizio (RM), J. Kovacic (JK)

    - NV: Presentation concerning experiments on TCV performed during the last MST1 experimental campaigns plus
     presentation of the draft of shot plan for W24
    - VN Raised question if it worth doing H-Mode during the the first Week of Operation. NV answer he would keep the
      search for scenario in June not to loose all the October part in searching a good H-Mode reference plasma. CT
      pointed out that a lot of H-Mode is foreseen for Topic 24 during the same week so they can be combined
    - CT suggested to concentrate on few topics (shoulder/divertor for example) but both FM and VN pointed that at least
      in other machines the two processes seemd unrelated
    - CT pointed out correctly that the proposed current scan overestimated maximum values of toroidal field achievable
      and needs to be readjusted
    - FM pointed out the importance of neutrals in the process of shoulder formation and that all the
      different scenarios need a detailed studies in the difference in neutral
    - VN pointed out that Bt reversal is an issue which needs to be addressed although both CT and NV suggested
      that a similar experiments has been performed in the last experiment
    - CT explained the new capability of probe head
    - CT suggested the need to explore the low collisionality part of the diagram and to
      look carefully of differences in ExB shearing in the different regime, to understand if SOL transport
      changes can be motivated by different shearing rate
    - VN suggested the possibility to look more carefully into neutrals also considering eventually N seeding
      in L-Mode
    - VN pointed out that a possibility would be to perform the vertical scan by keeping both the divertor leg on
      the inner wall in order not to have too different divertor condition. In this way we can have measurements
      at different poloidal position
    
    Following the discussion the following todo list arised
    - [ ] Check already existing measurements, also in terms of fluctuations, in vertical shifted plasmas
    - [ ] Check already existing measuerements in L-Mode N seed discharges also in terms of fluctuations
    - [ ] Redraft the program including part at lower collisionality
    - [ ] Check availability of DBS flow profile at the edge
    - [ ] Search of possible combination of H-Mode part together with Topic 24 which will be performed in the
          same week.
    - [ ] Circulate new program and new ideas by the end of next week
*** AUG-Data analysis meeting 15.09.2017
**** Agenda
     1. Introduction and Data evaluation (N. Vianello)
     2. Neutrals data analysis from camera (M. Agostini)
     3. Evaluation of wall mounted probes (S. Costea)
     4. Modelling of fast electrons associated with ELM filament eruption in AUG (K. McClements)
     5. Discussion and determination of task-lists
     6. Brainstorming on 2018 AUG campaign
**** Connection details
     SUMMARY for Channel 2 / 15Sep2017: AUG topic 21 Meeting: 
     Presentation: https://tv.euro-fusion.org/channel2/home 
     Presentation Password: topic21 
     Video-conference nr. (H.323): 004910097920062 
     ISDN: +49-30-20097920062 (ConferenceID = 97920062) 
**** Participants
     N. Vianello, M. Agostini, A. Hakkola, C.Tsui, J. Vicente, K. McClements, J.J.Rasmussen, C. Tsui,
     M. Spolaore, S. Costea,  F. Militello, V. Naulin
**** Minutes
     - Presentations
       1. N. Vianello: Presentation on the status of analysis. F. Militello asked clarification on the
	  differences in H-mod with/without cryopumps and pointed out the similarity with JET results
	  in corner configuration.
       2. M. Agostini: Presentation on Dalpha and KN1D. Suggestion to use divertor information on density and
	  temperatures (Probes/stark broadening other??)
       3. S. Costea: Presentation from wall mounted probe. Change of PDF shape at different Lambda. Mean and std
	  as a function of Lambda. Argued that the signal are too noisy check if they are in the limiter shadow.
       4. K. McClements: Possible hints on fast electrons coming from langmuir probes characteristics?
     - Brainstorming for 2018 campaign postponed. The SCs again ask for possible ideas on 2018 AUG campaigns. A. Hakola
       suggests that 2018 experimental time will not be sensibly shortened next year for MST1 as well as manpower for which
       a modest reduction is foreseen
     - N. Vianello restate the necessity to distribute the ideas for analysis and interpretation using all the possible
       communication channels
     
*** COMPASS meeting 19.09.17
**** Participants:
     N. Vianello, A. Hakola, M. Bernert, D. Carralero, J. Adamek,
**** Presentation
     - Presentation from J. Adamek on the COMPASS proposal
       - Bt 1.38, Ip=160 kA Ohmic or NBI-heated L-Modes with constant gas puff
**** Questions
     - Measurements of the parallel flow is feasible? *Yes*
     - Connection length in the private flux region?
     - How many plunges for shot? *1*
     - Density scan or density ramp? *density scan in between shots*
     
**** Notes
     We agree on the following things:
     - The probe head will be arranged with Jsat for measurement of parallel flow and changes
       in between the shots to ensure both Fast Te and filaments velocity
     - We have proposed to focus on L-Mode part only. In case of contingency shots are available we proposed
       to make a different point in L_{parallel}. Given the short leg length in COMPASS it would be better
       to increase the parallel connection lenght means reducint Bt at same current level
     - Thomson profile available at 90 Hz
     - Li-Be every 4 microsecond *Contact Hungarian people*
     - Dalpha available HFS/LFS but not at the diverto
     - No Infrared available
*** TCV meeting 13.10.17
**** Participants
     N. Vianello, M. Agostini, A. Hakkola, V. Naulin, F. Militello
     B. Labit, C. Theiler, C.Tsui
**** Presentation and Minutes
     - N. Vianello: point from Christian on the fact that for TCV we need
       detachment and roll-over which is not reached for the constant q95
       scan. *This can be consistent with the fact the SOL flattening is not obtained*
     - B. Labit: found and appropriate reference for H-Mode *Shot 55860* needs shape
       adjustment for proper evaluation of target profile
     - C. Theiler: further reference at High Ip to be explored together with
       N seeding
     - A. Hakkola: suggests the need to ask for further contingency shot
